export const resume = {
  summary: "Software Engineer with hands-on experience building real-time AI applications, backend services, data pipelines, and cloud-connected systems. Built voice AI agents, computer-vision systems, reproducible AI evaluation workflows, and operational data infrastructure using Python and modern cloud tooling. Electrical and Electronics Engineering graduate with a 4.80/5.00 CGPA, combining strong systems thinking with practical software delivery across AI, backend, and data-intensive environments.",
  skills: [
    { label: "Languages & Data", value: "Python, Scala, SQL, Bash, Pandas, NumPy" },
    { label: "Backend & Databases", value: "FastAPI, Django, Flask, PostgreSQL, MongoDB" },
    { label: "AI/ML", value: "TensorFlow, PyTorch, OpenCV, LangChain/LangGraph, RAG" },
    { label: "Cloud, DevOps & Data Systems", value: "Docker, Kubernetes, AWS, GCP, Git, CI/CD, Kafka, Airflow, Spark, MQTT" },
  ],
  experience: [
    { company: "Inspired Technologies", location: "Abuja", role: "Software Engineer", dates: "Dec 2025 – Jun 2026", bullets: ["Enabled context-aware voice interactions during live calls by engineering a low-latency AI agent pipeline with Agno and LiveKit, integrating tool calling, persistent memory, and real-time reasoning.","Connected field devices to cloud-based services by building backend systems for device-data processing, database operations, event logging, asynchronous jobs, and system communication.","Enabled real-time security monitoring and remote service deployment by integrating Roboflow-based object detection and deploying containerized AI/backend workloads with MQTT, Docker, Kubernetes, AWS, and GCP."]},
    { company: "AfterQuery", location: "US (Remote)", role: "Software Engineer", dates: "Oct 2025 – May 2026", bullets: ["Strengthened AI-system evaluation by designing deterministic command-line engineering tasks covering debugging, build automation, data processing, and environment configuration.","Standardized reproducible execution across AI evaluation workflows by developing Docker-based environments and applying CI/CD principles for cross-platform consistency.","Improved reliability of AI training and evaluation pipelines by authoring test suites, validation logic, and technical documentation for complex multi-step engineering tasks."]},
    { company: "National Center for AI and Robotics", location: "Abuja", role: "AI/ML Intern", dates: "Mar 2024 – Sep 2024", bullets: ["Automated blood-smear image analysis for malaria screening by developing a real-time diagnostic system with TensorFlow and OpenCV, reducing dependence on manual microscopy review.","Enabled responsive gesture recognition without cloud connectivity by engineering a lightweight offline inference pipeline for embedded devices and optimizing edge execution.","Automated vendor-document analysis and intelligent surveillance workflows by building a RAG-based processing application and integrating embedded image capture with facial-recognition and object-classification models."]},
    { company: "Transmission Company of Nigeria", location: "Abuja", role: "Data Engineer Intern", dates: "Jul 2023 – Sep 2023", bullets: ["Enabled continuous analysis of grid operating parameters by engineering Kafka-based ingestion pipelines for load-distribution and transformer data across service zones.","Converted unstructured field logs into analysis-ready datasets with Apache Spark and Pandas, supporting predictive-maintenance and operational-trend analysis.","Strengthened reliability assessments by identifying anomalies in grid data and orchestrating validated ETL workflows with Apache Airflow."]}
  ],
  education: "Covenant University — B.Eng. Electrical and Electronics Engineering · 2020–2025 · CGPA 4.80/5.00 · Ota, Ogun",
  certifications: "IBM Data Engineering · IBM Python for Data Science, AI & Development · DeepLearning.AI Deep Learning"
} as const;
